CREATE TABLE IF NOT EXISTS rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE, 						-- Уникальный адрес почты
    login VARCHAR(255) NOT NULL UNIQUE, 						-- логин
    name VARCHAR(255),                  						-- Имя пользователя
    birthday DATE
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,		-- ID пользователя, который инициирует дружбу
    friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE,	-- ID пользователя, которого добавляют в друзья
    status VARCHAR(20) DEFAULT 'pending',						-- Статус заявки
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),			-- Дата и время создания записи
    PRIMARY KEY (user_id, friend_id),							-- Первичный ключ по двум колонкам
    CONSTRAINT check_status 
        CHECK (status IN ('pending', 'accepted', 'blocked'))	-- Ограничение: разрешаем только эти три значения
);

CREATE TABLE IF NOT EXISTS film ( 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 	-- Уникальный ID
    name VARCHAR(50) NOT NULL, 									-- Название фильма
    description VARCHAR(200), 									-- Краткое описание фильма
    releaseDate DATE, 											-- Дата выхода фильма в прокат (тип данных: год-месяц-день)
    duration INTEGER, 											-- Продолжительность фильма в минутах
    genre_id INTEGER REFERENCES genre(id), 						-- Ссылка на ID жанра из таблицы genre (внешний ключ)
    rating_id INTEGER REFERENCES rating(id) 					-- Ссылка на ID рейтинга из таблицы rating (внешний ключ)
);

CREATE TABLE IF NOT EXISTS likes ( 
    film_id BIGINT REFERENCES film(id) ON DELETE CASCADE, 		-- ID фильма, при удалении фильма лайк удаляется автоматически
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, 		-- ID пользователя, при удалении пользователя лайк удаляется автоматически
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), 			-- Дата и время постановки лайка, по умолчанию — текущий момент
    PRIMARY KEY (film_id, user_id) 								-- Составной первичный ключ: один пользователь может лайкнуть один фильм только один раз
);