CREATE TABLE IF NOT EXISTS rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE, 						-- Уникальный адрес почты
    login VARCHAR(255) NOT NULL UNIQUE, 						-- логин
    name VARCHAR(255),                  						-- Имя пользователя
    birthday DATE
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,		-- ID пользователя, который инициирует дружбу
    friend_id BIGINT REFERENCES users(id) ON DELETE CASCADE,	-- ID пользователя, которого добавляют в друзья
    status VARCHAR(20) DEFAULT 'pending',						-- Статус заявки
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),			-- Дата и время создания записи
    PRIMARY KEY (user_id, friend_id)							-- Первичный ключ по двум колонкам
--    CONSTRAINT check_status
--        CHECK (status IN ('pending', 'accepted', 'blocked'))	-- в DBeaver скрипты работают, в постман работает, интеграционные тесты падают.
);

CREATE TABLE IF NOT EXISTS film ( 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200),
    releaseDate DATE,
    duration INTEGER,
    rating_id INTEGER REFERENCES rating(id)
);

CREATE TABLE IF NOT EXISTS likes ( 
    film_id BIGINT REFERENCES film(id) ON DELETE CASCADE, 		-- ID фильма, при удалении фильма лайк удаляется автоматически
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, 		-- ID пользователя, при удалении пользователя лайк удаляется автоматически
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), 			-- Дата и время постановки лайка, по умолчанию — текущий момент
    PRIMARY KEY (film_id, user_id) 								-- Составной первичный ключ: один пользователь может лайкнуть один фильм только один раз
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT REFERENCES film(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

MERGE INTO genre (genre) KEY(genre)
VALUES
    ('Комедия'),
    ('Драма'),
    ('Мультфильм'),
    ('Триллер'),
    ('Документальный'),
    ('Боевик');

MERGE INTO rating (rating) KEY(rating)
VALUES
    ('G'),
    ('PG'),
    ('PG-13'),
    ('R'),
    ('NC-17')
